name: Update README with progress

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update README
        run: |
          python update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Update README with progress"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
