name: Update README progress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest  # 或者使用你需要的其他运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run update_readme.py
      run: python update_readme.py  # 运行脚本更新 README.md 文件

    - name: Commit updated README.md
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add README.md
        git commit -m "Update progress in README.md" || echo "No changes to commit"
        git push origin main
